# See http://www.appveyor.com/docs/appveyor-yml for many more options

environment:
  NuGetApiKey:
    secure: 0gKIN7P/STYmuqoaIHUTQB9RCwKMLZJXNO96jALWlvYNZ5DQ7k0zi9YYxWhMrwS4

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*|update readme.*s/

install:
  - cinst pester
  - ps: Install-PackageProvider -Name NuGet -Force | Out-Null
  - ps: Install-Module PsScriptAnalyzer -Force | Out-Null

build: false

test_script:
# Test with native PS version
  - ps: . .\Tests\appveyor.pester.ps1
# Finalize pass - collect and upload results
  - ps: . .\Tests\appveyor.pester.ps1 -Finalize