function Get-DokuPageVersionInfo {
<#
	.SYNOPSIS
		Returns information about a specific version of a Wiki page
	
	.DESCRIPTION
		Returns information about a specific version of a Wiki page
	
	.PARAMETER DokuSession
		The DokuSession (generated by New-DokuSession) from which to get the page info.
	
	.PARAMETER FullName
		The full page name for which to return the data
	
	.PARAMETER VersionTimestamp
		The timestamp for which version to get the info from
	
	.EXAMPLE
		PS C:\> $PageInfo = Get-DokuPageVersionInfo -DokuSession $DokuSession -FullName "namespace:namespace:page" -VersionTimestamp 1497464418
	
	.OUTPUTS
		System.Management.Automation.PSObject
	
	.NOTES
		AndyDLP - 2018-05-26
#>
	
	[CmdletBinding()]
	[OutputType([psobject])]
	param
	(
		[Parameter(Mandatory = $true,
				   Position = 1,
				   HelpMessage = 'The DokuSession from which to get the page info')]
		[ValidateNotNullOrEmpty()]
		[psobject]$DokuSession,
		[Parameter(Mandatory = $true,
				   Position = 2,
				   HelpMessage = 'The full page name for which to return the data')]
		[ValidateNotNullOrEmpty()]
		[string]$FullName,
		[Parameter(Mandatory = $true,
				   Position = 3,
				   HelpMessage = 'The timestamp for which version to get the info from')]
		[ValidateNotNullOrEmpty()]
		[int]$VersionTimestamp
	)
	
	$payload = (ConvertTo-XmlRpcMethodCall -Name "wiki.getPageInfoVersion" -Params @($FullName, $VersionTimestamp)) -replace "String", "string"
	$payload = $payload -replace "Int32", "i4"
	if ($DokuSession.SessionMethod -eq "HttpBasic") {
		$httpResponse = Invoke-WebRequest -Uri $DokuSession.TargetUri -Method Post -Headers $DokuSession.Headers -Body $payload -ErrorAction Stop
	} else {
		$httpResponse = Invoke-WebRequest -Uri $DokuSession.TargetUri -Method Post -Headers $DokuSession.Headers -Body $payload -ErrorAction Stop -WebSession $DokuSession.WebSession
	}
	
	$ArrayValues = ([xml]$httpResponse.Content | Select-Xml -XPath "//struct").Node.Member.Value.Innertext
	$PageObject = New-Object PSObject -Property @{
		FullName = $FullName
		LastModified = Get-Date -Date ($ArrayValues[1])
		Author = $ArrayValues[2]
		VersionTimestamp = $ArrayValues[3]
		PageName = ($FullName -split ":")[-1]
		ParentNamespace = ($FullName -split ":")[-2]
		RootNamespace = ($FullName -split ":")[0]
	}
	return $PageObject
}