function Get-DokuServerTime {
<#
	.SYNOPSIS
		Returns the current time from the remote wiki server as Unix timestamp
	
	.DESCRIPTION
		Returns the current time from the remote wiki server as Unix timestamp
	
	.PARAMETER DokuSession
		The DokuSession (generated by New-DokuSession) from which to get the page list.
	
	.PARAMETER Raw
		Output the raw response from the server in UNIX time rather than a DateTime
	
	.EXAMPLE
		PS C:\> $serverTime = Get-DokuServerTime -DokuSession $DokuSession
	
	.EXAMPLE
		PS C:\> $UnixserverTime = Get-DokuServerTime -DokuSession $DokuSession -Raw
	
	.OUTPUTS
		System.DateTime, System.Int32
	
	.NOTES
		AndyDLP - 2018-05-26
#>
	
	[CmdletBinding()]
	[OutputType([datetime], [int])]
	param
	(
		[Parameter(Mandatory = $true,
				   Position = 1,
				   HelpMessage = 'The DokuSession from which to get the page list.')]
		[ValidateScript({ ($_.WebSession -ne $null) -or ($_.Headers.Keys -contains "Authorization") })]
		[psobject]$DokuSession,
		[Parameter(Position = 2,
				   HelpMessage = 'Output the raw response from the server in UNIX time')]
		[switch]$Raw
	)
	
    # No parameters is still creating the value key
	$payload = (ConvertTo-XmlRpcMethodCall -Name "dokuwiki.getTime") -replace "<value></value>",""
	if ($DokuSession.SessionMethod -eq "HttpBasic") {
		$httpResponse = Invoke-WebRequest -Uri $DokuSession.TargetUri -Method Post -Headers $DokuSession.Headers -Body $payload -ErrorAction Stop
	} else {
		$httpResponse = Invoke-WebRequest -Uri $DokuSession.TargetUri -Method Post -Headers $DokuSession.Headers -Body $payload -ErrorAction Stop -WebSession $DokuSession.WebSession
	}
	
	[int]$RawDokuTime = ([xml]$httpResponse.Content | Select-Xml -XPath "//value/int").Node.InnerText
	if ($Raw) {
		return $RawDokuTime
	} else {
		return [datetime]$RawDokuTime
	}
}