function Get-DokuTitle {
<#
	.SYNOPSIS
		Returns the title of the wiki

	.DESCRIPTION
		Returns the title of the wiki

	.PARAMETER DokuSession
		The DokuSession (generated by New-DokuSession) from which to get the wiki title.

	.EXAMPLE
		PS C:\> $DokuTitleObj = Get-DokuTitle -DokuSession $DokuSession

	.EXAMPLE
		PS C:\> $DokuTitleObj = Get-DokuTitle -DokuSession $DokuSession

	.OUTPUTS
		System.Management.Automation.PSObject

	.NOTES
		AndyDLP - 2018-05-26
#>

	[CmdletBinding(PositionalBinding = $true)]
	[OutputType([psobject])]
	param
	(
		[Parameter(Mandatory = $true,
				   Position = 1,
				   ValueFromPipeline = $true,
				   HelpMessage = 'The DokuSession from which to get the wiki title.')]
		[ValidateNotNullOrEmpty()]
		[psobject]$DokuSession
	)

	begin {

	} # begin

	process {
		$APIResponse = Invoke-DokuApiCall -DokuSession $DokuSession -MethodName 'dokuwiki.getTitle' -MethodParameters @()
		if ($APIResponse.CompletedSuccessfully -eq $true) {
			[string]$DokuTitle = ($APIResponse.XMLPayloadResponse | Select-Xml -XPath "//value/string").node.InnerText
			$TitleObject = New-Object PSObject -Property @{
				Server = $DokuSession.Server
				Title = $DokuTitle
			}
			$TitleObject
		} elseif ($null -eq $APIResponse.ExceptionMessage) {
			Write-Error "Fault code: $($APIResponse.FaultCode) - Fault string: $($APIResponse.FaultString)"
		} else {
			Write-Error "Exception: $($APIResponse.ExceptionMessage)"
		}
	} # process

	end {

	} # end
}