function Invoke-DokuApiCall {
<#
    .SYNOPSIS
        Invokes the 

    .DESCRIPTION
        Gets an array of all pages from an instance of DokuWiki.

    .PARAMETER DokuSession
        The DokuSession (generated by New-DokuSession) from which to get the page list.

    .PARAMETER MethodName
        The method name to invoke

    .PARAMETER MethodParameters
       The parameters for the specified method

    .EXAMPLE
        PS C:\> $httpResponse = Invoke-DokuApiCall -DokuSession $DokuSession -MethodName wiki.getAllPages

    .OUTPUTS
        Microsoft.PowerShell.Commands.HtmlWebResponseObject

    .NOTES
        AndyDLP - 2019-01-24
#>

    [CmdletBinding()]
    [OutputType([Microsoft.PowerShell.Commands.HtmlWebResponseObject])]
    param
    (
        [Parameter(Mandatory = $true,
                    Position = 1,
                    ValueFromPipeline = $true,
                    ValueFromPipelineByPropertyName = $true,
                    HelpMessage = 'The DokuSession from which to get the page list')]
        [ValidateScript({ ($null -ne $_.WebSession) -or ($_.Headers.Keys -contains "Authorization") })]
        [PSObject]$DokuSession,

        [Parameter(Mandatory = $true,
                    Position = 2,
                    ValueFromPipeline = $true,
                    ValueFromPipelineByPropertyName = $true,
                    HelpMessage = 'The method name to invoke')]
        [ValidateNotNullOrEmpty()]
        [string]$MethodName,

        [Parameter(Mandatory = $false,
                    Position = 3,
                    ValueFromPipeline = $true,
                    ValueFromPipelineByPropertyName = $true,
                    HelpMessage = 'The parameters for the specified method')]
        [array]$MethodParameters
    )

    begin {
        Write-Debug "$($MyInvocation.MyCommand.Name):: Function started"
    } # begin

    process {
        $payload = ConvertTo-XmlRpcMethodCall -Name $MethodName -Params $MethodParameters
        Write-Debug "XMLRPC payload: $payload"

        $params = @{
            Uri = $DokuSession.TargetUri
            Method = 'Post'
            Headers = $DokuSession.Headers
            Body = $payload
            ErrorAction = 'Stop'
        }
        if ($DokuSession.SessionMethod -eq "Cookie") {
            $params.Add('WebSession',$DokuSession.WebSession)
        }

        try {
            $httpResponse = Invoke-WebRequest @params
            $XMLContent = [xml]($httpResponse.Content)
            if ($null -ne ($xml | Select-Xml -XPath "//fault").node) {
                # Web request worked but failed on API side
            } else {
                
            }
            return $httpResponse
        }
        catch [System.Net.WebException] {
            # 401 unauthorized - faultCode -32603 faultString server error. not authorized to call method XXXXXX
            # ?? find other errors
            Write-Error "Caught by exception type: [System.Net.WebException]"
            Write-Error $PSItem
        }
        catch {
            # Catch other errors
            Write-Error $PSItem
        }
    } # process

    end {
        Write-Debug "$($MyInvocation.MyCommand.Name):: Function ended"
    } # end
}