function Search-DokuWiki {
<#
	.SYNOPSIS
		Search DokuWiki instance for matching pages
	
	.DESCRIPTION
		Returns an array of matching pages similar to what is returned by Get-DokuPageList, snippets are provided for the first 15 results
	
	.PARAMETER DokuSession
		The DokuSession (generated by New-DokuSession) from which to get the matching pages.
	
	.PARAMETER SearchString
		The search string to match pages against, see 'https://www.dokuwiki.org/search' for syntax details
	
	.EXAMPLE
		PS C:\> $MatchingPages = Search-DokuWiki -DokuSession $DokuSession -SearchString "VSS Admin"
	
	.OUTPUTS
		System.Management.Automation.PSObject[]
	
	.NOTES
		AndyDLP - 2018-05-26
#>
	
	[CmdletBinding()]
	[OutputType([psobject[]])]
	param
	(
		[Parameter(Mandatory = $true,
				   Position = 1,
				   HelpMessage = 'The DokuSession from which to get the matching pages.')]
		[ValidateNotNullOrEmpty()]
		[psobject]$DokuSession,
		[Parameter(Mandatory = $true,
				   Position = 2,
				   HelpMessage = 'The search string to match pages against')]
		[ValidateNotNullOrEmpty()]
		[string]$SearchString
	)
	
	$payload = (ConvertTo-XmlRpcMethodCall -Name "dokuwiki.search" -Params @($SearchString)) -replace "String","string"
	if ($DokuSession.SessionMethod -eq "HttpBasic") {
		$httpResponse = Invoke-WebRequest -Uri $DokuSession.TargetUri -Method Post -Headers $DokuSession.Headers -Body $payload -ErrorAction Stop
	} else {
		$httpResponse = Invoke-WebRequest -Uri $DokuSession.TargetUri -Method Post -Headers $DokuSession.Headers -Body $payload -ErrorAction Stop -WebSession $DokuSession.WebSession
	}
	
	$MemberNodes = ([xml]$httpResponse.Content | Select-Xml -XPath "//struct").Node
	foreach ($node in $MemberNodes) {
		$PageObject = New-Object PSObject -Property @{
			FullName = (($node.member)[0]).value.string
			Score = (($node.member)[1]).value.int
			Revision = (($node.member)[2]).value.int
			ModifiedTime = (($node.member)[3]).value.int
			Size = (($node.member)[4]).value.int
			Snippet = (($node.member)[5]).value.string
			Title = (($node.member)[6]).value.string
			PageName = (((($node.member)[0]).value.string) -split ":")[-1]
			ParentNamespace = (((($node.member)[0]).value.string) -split ":")[-2]
			RootNamespace = (((($node.member)[0]).value.string) -split ":")[0]
		}
		[array]$AllDokuwikiPages = $AllDokuwikiPages + $PageObject
	}
	return $AllDokuwikiPages
}